language: php

php:
  - '7.1'

before_install:
  - composer config -g github-oauth.github.com ${GH_TOKEN}

script:
  - make

deploy:
  provider: pages
  edge:
    branch: v1.8.47
  github-token: ${GH_TOKEN}
  skip-cleanup: true
  local-dir: public
  keep-history: true
  email: deploy@travis-ci.org
  name: Travis CI
  on:
    branch: master

notifications:
  webhooks:
    - https://h2a-hubot.herokuapp.com/webhooks/travis
