language: php

php:
  - '7.1'

script:
  - composer config -g github-oauth.github.com ${GH_TOKEN}
  - composer deploy

notifications:
  webhooks:
    - https://h2a-hubot.herokuapp.com/webhooks/travis
