# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink: pretty

# Server
source:         "."
destination: ./public
baseurl: '/satis'
url: https://howtoadhd.github.io
theme: jekyll-theme-howtoadhd
encoding: UTF-8

title: Satis
description: Composer all the things.
